# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: bumper
    main: ./cmd/bumper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - "-s -w -X github.com/disintegrator/bumper/buildinfo.Commit={{.FullCommit}} -X github.com/disintegrator/bumper/buildinfo.Version={{.Version}} -X github.com/disintegrator/bumper/buildinfo.Date={{.Date}}"

archives:
  - id: bumper
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - homepage: https://github.com/disintegrator/bumper
    description: Manage versioning and changelogs for your projects.
    license: MPL-2.0
    maintainer: Georges Haidar <ghaida0@gmail.com>
    formats:
      - apk
      - deb
      - rpm
      - archlinux

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: '${artifact}.keyless.sig'
    certificate: '${artifact}.pem'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes

changelog:
  disable: false

release:
  github: {}
  prerelease: auto
  mode: keep-existing