# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: bumper-cli
    main: ./cmd/bumper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - "-s -w -X github.com/disintegrator/bumper/buildinfo.Commit={{.FullCommit}} -X github.com/disintegrator/bumper/buildinfo.Version={{.Version}} -X github.com/disintegrator/bumper/buildinfo.Date={{.Date}}"

archives:
  - id: bumper-cli
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

signs:
  - cmd: cosign
    signature: '${artifact}.keyless.sig'
    certificate: '${artifact}.pem'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes

changelog:
  disable: false

release:
  github: {}
  prerelease: auto
  mode: keep-existing