name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: [ VERSION ]

jobs:
  release-cli:
    runs-on: ubuntu-latest
    permissions:
      # So we can push tags
      contents: write
      # For keyless signing with cosign
      id-token: write
    env:
      BUMPER_GROUP: bumper
    steps:
      - name: Checkout repository
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Mise
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4.2.3
        with:
          install: true
          cache: true
          env: false
      
      - name: Set up Bun
        run: bun install --filter=.

      - name: Prepare cache keys
        run: mise run gha:pre-cache

      - name: Cache Go modules and build cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}

      - name: Set up env
        run: |
          notes_file="$(mktemp)"
          bumper_version="$(mise bumper current)"
          echo "BUMPER_GROUP_VERSION=$bumper_version" >> $GITHUB_ENV
          echo "GORELEASER_CURRENT_TAG=v$bumper_version" >> $GITHUB_ENV
          echo "RELEASE_NOTES_FILE=$notes_file" >> $GITHUB_ENV
          mise bumper cat --version "$bumper_version" > "$notes_file"

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${GORELEASER_CURRENT_TAG}"
          git push origin "${GORELEASER_CURRENT_TAG}"

      - name: Install cosign
        uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # v3.10.1

      - name: goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: --release-notes=${{ env.RELEASE_NOTES_FILE }} --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
